package com.skx.tomike.bomber

const val ROUTER_FIRST_LEVEL_BASICS = "/javaBasics"
const val ROUTER_FIRST_LEVEL_COROUTINE = "/coroutine"
const val ROUTER_FIRST_LEVEL_THREAD = "/thread"

const val ROUTE_PATH_BASE64 = "${ROUTER_FIRST_LEVEL_BASICS}/base64"
const val ROUTE_PATH_GSON = "${ROUTER_FIRST_LEVEL_BASICS}/gson"
const val ROUTE_PATH_URL_ENCODE = "${ROUTER_FIRST_LEVEL_BASICS}/url/encode"
const val ROUTE_PATH_URL_PARSE = "${ROUTER_FIRST_LEVEL_BASICS}/url/parse"
const val ROUTE_PATH_XML_PARSE = "${ROUTER_FIRST_LEVEL_BASICS}/xml/parse"
const val ROUTE_PATH_GENERIC = "${ROUTER_FIRST_LEVEL_BASICS}/generic"
const val ROUTE_PATH_REFLECT = "${ROUTER_FIRST_LEVEL_BASICS}/reflect"

const val ROUTE_PATH_COROUTINE = "${ROUTER_FIRST_LEVEL_COROUTINE}/coroutine"

const val ROUTE_PATH_THREAD_START = "${ROUTER_FIRST_LEVEL_THREAD}/start"
const val ROUTE_PATH_THREAD_CALL_BACK = "${ROUTER_FIRST_LEVEL_THREAD}/callback"
const val ROUTE_PATH_THREAD_COMMUNICATION = "${ROUTER_FIRST_LEVEL_THREAD}/communication"
const val ROUTE_PATH_THREAD_DAEMON = "${ROUTER_FIRST_LEVEL_THREAD}/daemon"
const val ROUTE_PATH_THREAD_INTERRUPT = "${ROUTER_FIRST_LEVEL_THREAD}/interrupt"
const val ROUTE_PATH_THREAD_POOL = "${ROUTER_FIRST_LEVEL_THREAD}/pool"
const val ROUTE_PATH_THREAD_EXECUTORS = "${ROUTER_FIRST_LEVEL_THREAD}/executors"
const val ROUTE_PATH_THREAD_SYNCHRONIZED = "${ROUTER_FIRST_LEVEL_THREAD}/synchronized"
const val ROUTE_PATH_THREAD_REENTRANT_LOCK = "${ROUTER_FIRST_LEVEL_THREAD}/reentrantlock"
