package com.skx.tomike.tank


const val ROUTER_FIRST_LEVEL_widget = "/widget" // view
const val ROUTER_FIRST_LEVEL_anim = "/anim" // 动画
const val ROUTER_FIRST_LEVEL_linkage = "/linkage" // 联动
const val ROUTER_FIRST_LEVEL_transition = "/transition" // 转场

const val ROUTE_PATH_TWEEN = "${ROUTER_FIRST_LEVEL_anim}/tween"
const val ROUTE_PATH_PROPERTY = "${ROUTER_FIRST_LEVEL_anim}/property"
const val ROUTE_PATH_SHAKE = "${ROUTER_FIRST_LEVEL_anim}/shake"
const val ROUTE_PATH_CIRCULAR_REVEAL = "${ROUTER_FIRST_LEVEL_anim}/circular/reveal"
const val ROUTE_PATH_SCROLLER = "${ROUTER_FIRST_LEVEL_anim}/scroller"
const val ROUTE_PATH_LAYOUT_TRANSITION = "${ROUTER_FIRST_LEVEL_anim}/layout/transition"
const val ROUTE_PATH_BEZIER = "${ROUTER_FIRST_LEVEL_anim}/bezier"

const val ROUTE_PATH_scroll_change_title = "${ROUTER_FIRST_LEVEL_linkage}/scroll/changeTitle"
const val ROUTE_PATH_scroll_anchor = "${ROUTER_FIRST_LEVEL_linkage}/scroll/anchor"
const val ROUTE_PATH_scroll_zoom = "${ROUTER_FIRST_LEVEL_linkage}/scroll/zoom"
const val ROUTE_PATH_scroll_zoom2 = "${ROUTER_FIRST_LEVEL_linkage}/scroll/zoom2"

const val ROUTE_PATH_share_Element = "${ROUTER_FIRST_LEVEL_transition}/shareElement"

const val ROUTE_PATH_VIEW_FOCUS = "${ROUTER_FIRST_LEVEL_widget}/View/focus"
const val ROUTE_PATH_TEXTVIEW_SELECTABLE = "${ROUTER_FIRST_LEVEL_widget}/TextView/selectable"
const val ROUTE_PATH_TEXTVIEW_WORD_SPACE = "${ROUTER_FIRST_LEVEL_widget}/TextView/wordSpace"
const val ROUTE_PATH_TEXTVIEW_SPANNABLESTRING = "${ROUTER_FIRST_LEVEL_widget}/TextView/spannableString"
const val ROUTE_PATH_EDITTEXT_LIGHT2DARK = "${ROUTER_FIRST_LEVEL_widget}/EditText/light2dark"
const val ROUTE_PATH_EDITTEXT_LOWER2UPPER = "${ROUTER_FIRST_LEVEL_widget}/EditText/lower2upper"
const val ROUTE_PATH_EDITTEXT_CURSOR = "${ROUTER_FIRST_LEVEL_widget}/EditText/cursor"
const val ROUTE_PATH_TEXTSWITCH = "${ROUTER_FIRST_LEVEL_widget}/TextSwitch"
const val ROUTE_PATH_CARDVIEW = "${ROUTER_FIRST_LEVEL_widget}/CardView"
const val ROUTE_PATH_CHECKBOX = "${ROUTER_FIRST_LEVEL_widget}/CheckBox"
const val ROUTE_PATH_FLOATINGACTIONBUTTON = "${ROUTER_FIRST_LEVEL_widget}/FloatingActionButton"
const val ROUTE_PATH_RADIOGROUP = "${ROUTER_FIRST_LEVEL_widget}/RadioGroup"
const val ROUTE_PATH_MATRIXIMAGE = "${ROUTER_FIRST_LEVEL_widget}/MatrixImage"
const val ROUTE_PATH_SHAPE_VIEW = "${ROUTER_FIRST_LEVEL_widget}/ShapeView"
const val ROUTE_PATH_CONSTRAINT_LAYOUT = "${ROUTER_FIRST_LEVEL_widget}/ConstraintLayout"
const val ROUTE_PATH_NAVIGATION_BAR = "${ROUTER_FIRST_LEVEL_widget}/NavigationBarLayout"
const val ROUTE_PATH_COORDINATOR = "${ROUTER_FIRST_LEVEL_widget}/CoordinatorLayout"
const val ROUTE_PATH_COORDINATOR2 = "${ROUTER_FIRST_LEVEL_widget}/CoordinatorLayout2"
const val ROUTE_PATH_DRAWER_LAYOUT = "${ROUTER_FIRST_LEVEL_widget}/DrawerLayout"
const val ROUTE_PATH_FLOW_LAYOUT = "${ROUTER_FIRST_LEVEL_widget}/FlowLayout"
const val ROUTE_PATH_PAGE_INDICATOR_LAYOUT = "${ROUTER_FIRST_LEVEL_widget}/PageIndicatorLayout"
const val ROUTE_PATH_RECYCLER_STAGGERED_GRID = "${ROUTER_FIRST_LEVEL_widget}/RecyclerView/StaggeredGrid"
const val ROUTE_PATH_RECYCLER_AS_VP = "${ROUTER_FIRST_LEVEL_widget}/RecyclerView/asViewPager"
const val ROUTE_PATH_RECYCLER_CHILD_COUNT = "${ROUTER_FIRST_LEVEL_widget}/RecyclerView/childCount"
const val ROUTE_PATH_RECYCLER_COUNT_DOWN = "${ROUTER_FIRST_LEVEL_widget}/RecyclerView/countdown"
const val ROUTE_PATH_RECYCLER_ITEM_UPDATE = "${ROUTER_FIRST_LEVEL_widget}/RecyclerView/itemUpdate"
const val ROUTE_PATH_RECYCLER_SCROLL2POS = "${ROUTER_FIRST_LEVEL_widget}/RecyclerView/scroll2pos"
const val ROUTE_PATH_VIEWPAGER2 = "${ROUTER_FIRST_LEVEL_widget}/ViewPager2"
const val ROUTE_PATH_VIEWPAGER_LOOP = "${ROUTER_FIRST_LEVEL_widget}/ViewPager/loop"
const val ROUTE_PATH_VIEWPAGER_MULTIPLE_PAGE = "${ROUTER_FIRST_LEVEL_widget}/ViewPager/multiplePage"
const val ROUTE_PATH_VIEWPAGER_WRAP_CONTENT = "${ROUTER_FIRST_LEVEL_widget}/ViewPager/wrapContent"
const val ROUTE_PATH_SCROLLVIEW_RV = "${ROUTER_FIRST_LEVEL_widget}/ScrollView/recyclerview"
const val ROUTE_PATH_NSCROLLVIEW_VP = "${ROUTER_FIRST_LEVEL_widget}/NScrollView/viewpager"
const val ROUTE_PATH_SHADOW = "${ROUTER_FIRST_LEVEL_widget}/shadow"
const val ROUTE_PATH_SNACKBAR = "${ROUTER_FIRST_LEVEL_widget}/SnackBar"
const val ROUTE_PATH_SWIPEREFRESH_LAYOUT = "${ROUTER_FIRST_LEVEL_widget}/SwipeRefreshLayout"
const val ROUTE_PATH_TABLELAYOUT_HELPER = "${ROUTER_FIRST_LEVEL_widget}/TableLayout/helper"
const val ROUTE_PATH_TABLELAYOUT_INDICATOR = "${ROUTER_FIRST_LEVEL_widget}/TableLayout/indicator"
const val ROUTE_PATH_GRADIENT_DRAWABLE = "${ROUTER_FIRST_LEVEL_widget}/GradientDrawable"
const val ROUTE_PATH_VECTOR_DRAWABLE = "${ROUTER_FIRST_LEVEL_widget}/VectorDrawable"
const val ROUTE_PATH_TINT = "${ROUTER_FIRST_LEVEL_widget}/tint"
const val ROUTE_PATH_TINT2 = "${ROUTER_FIRST_LEVEL_widget}/tint2"
